# EVALUACION 2

In [7]:
import pandas as pd
from sqlalchemy import create_engine

In [10]:
import os

# Credenciales por variables de entorno (nunca en el notebook)
usuario = os.getenv('PGUSER', 'postgres')
contraseña = os.getenv('PGPASSWORD', '')
host = os.getenv('PGHOST', 'localhost')
puerto = os.getenv('PGPORT', '5432')
base_de_datos = os.getenv('PGDATABASE', 'postgres')

In [13]:
conexion = f'postgresql+psycopg2://{usuario}:{contraseña}@{host}:{puerto}/{base_de_datos}'

In [16]:
conn = create_engine(conexion)
conn

Engine(postgresql+psycopg2://postgres:***@localhost:5432/postgres)

In [19]:
try:
    version = pd.read_sql("SELECT version();", conn).iloc[0, 0]
    print("Conexión exitosa con SQLAlchemy.")
    print(f"Versión del servidor PostgreSQL: {version}")
except Exception as e:
    print(f"Ocurrió un error al conectar con SQLAlchemy: {e}")

Conexión exitosa con SQLAlchemy.
Versión del servidor PostgreSQL: PostgreSQL 17.5 on x86_64-apple-darwin23.6.0, compiled by Apple clang version 16.0.0 (clang-1600.0.26.6), 64-bit

In [23]:
pd.read_sql('SELECT * FROM dw_aero.hc_rutas', conn)

       cod_ruta cod_aerolinea cod_aeropuerto_ori cod_aeropuerto_des
0             1         00410               2965               2990
1             2         00410               2966               2990
2             3         00410               2966               2962
3             4         00410               2968               2990
4             5         00410               2968               4078
...         ...           ...                ...                ...
67658     67659         04178               6334               3341
67659     67660         19016               4029               2912
67660     67661         19016               2912               4029
67661     67662         19016               2912               2913
67662     67663         19016               2913               2912

[67663 rows x 4 columns]

## Paso 1: Lectura fichero rutas.json y pasarlo a un Dataframe de Pandas.

In [28]:
df_rutas= pd.read_json("./ficheros/rutas.json")
df_rutas.head()

   cod_ruta cod_aeropuerto_ori cod_aeropuerto_des cod_aerolinea equipamiento
0         1               2965               2990         00410          CR2
1         2               2966               2990         00410          CR2
2         3               2966               2962         00410          CR2
3         4               2968               2990         00410          CR2
4         5               2968               4078         00410          CR2

## Paso2: Revisar si hay nulos en algunos de los campos. Si hay nulos en campos sustituirlospor el valor indeterminado de tipo ‘Z…9’ ajustado a la longitud del campo, es decir, Z con tantos 9 como haga falta para completar la longitud del campo.

In [33]:
df_rutas.isnull().values.any()

True

In [38]:
df_rutas.isnull().sum()

cod_ruta               0
cod_aeropuerto_ori     0
cod_aeropuerto_des     0
cod_aerolinea          0
equipamiento          18
dtype: int64

La unica columna que tiene nulos es el de 'equipamiento' por lo que veremos cual es su estructura

#### Reemplazo nulos 'equipamiento' (3 pos - Z99)

In [53]:
df_rutas[df_rutas['equipamiento'].isnull()]

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,equipamiento
2963,2964,7098,5967,Z9999,None
2964,2965,7090,5967,Z9999,None
3571,3572,3682,3858,03976,None
3583,3584,3442,7018,03976,None
3593,3594,3858,3682,03976,None
3602,3603,7018,3442,03976,None
4722,4723,3673,3861,00024,None
5909,5910,1881,1885,00024,None
6147,6148,3861,3673,00024,None
14417,14418,3682,3670,01355,None
14520,14521,0340,3682,01355,None
20523,20524,3502,3682,02009,None
21978,21979,0193,3682,02009,None
37168,37169,3774,3429,00109,None
37169,37170,3429,3774,00109,None
44937,44938,3682,3797,00028,None
47295,47296,3682,3550,04091,None
63444,63445,3682,3806,04547,None

In [59]:
df_rutas['equipamiento'] = df_rutas['equipamiento'].fillna('Z99')

In [62]:
df_rutas[df_rutas['equipamiento']=='Z99']

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,equipamiento
2963,2964,7098,5967,Z9999,Z99
2964,2965,7090,5967,Z9999,Z99
3571,3572,3682,3858,03976,Z99
3583,3584,3442,7018,03976,Z99
3593,3594,3858,3682,03976,Z99
3602,3603,7018,3442,03976,Z99
4722,4723,3673,3861,00024,Z99
5909,5910,1881,1885,00024,Z99
6147,6148,3861,3673,00024,Z99
14417,14418,3682,3670,01355,Z99
14520,14521,0340,3682,01355,Z99
20523,20524,3502,3682,02009,Z99
21978,21979,0193,3682,02009,Z99
37168,37169,3774,3429,00109,Z99
37169,37170,3429,3774,00109,Z99
44937,44938,3682,3797,00028,Z99
47295,47296,3682,3550,04091,Z99
63444,63445,3682,3806,04547,Z99

In [48]:
consulta_tabla= """
SELECT 
  column_name, 
  data_type, 
  character_maximum_length, 
  is_nullable, 
  column_default 
FROM 
  information_schema.columns 
WHERE 
  table_name = 'hc_rutas'
ORDER BY 
  ordinal_position;
"""

pd.read_sql(consulta_tabla, conn)

,column_name,data_type,character_maximum_length,is_nullable,column_default
0,cod_ruta,integer,NaN,NO,None
1,cod_aerolinea,character varying,5.0,YES,None
2,cod_aeropuerto_ori,character varying,4.0,YES,None
3,cod_aeropuerto_des,character varying,4.0,YES,None

Aunque por lo que podemos ver en el dataframe no existe la columna de 'equipamiento' por lo que vamos a borrarla

In [68]:
df_rutas.drop('equipamiento', axis=1, inplace=True)

In [71]:
# Revisamos de nuevo los nulos
df_rutas.isnull().sum()

cod_ruta              0
cod_aeropuerto_ori    0
cod_aeropuerto_des    0
cod_aerolinea         0
dtype: int64

## Paso3 - Validación de integridad: Comprobar si los aeropuertos (origen y destino) de las rutas existen en la tabla dm_aeropuertos. En caso de encontrar aeropuertos en el fichero de rutas que no estén en la tabla dm_aeropuertos actualizarlos a ‘Z999’.

#### Cargamos los datos de aeropuertos

In [83]:
df_aerop = pd.read_sql_query('SELECT cod_aeropuerto, nombre_aeropuerto FROM dw_aero.dm_aeropuertos', conn)
df_aerop.head()

  cod_aeropuerto           nombre_aeropuerto
0           0001                      Goroka
1           0002                      Madang
2           0003                 Mount Hagen
3           0004                      Nadzab
4           0005  Port Moresby Jacksons Intl

#### Realizamos el merge de ambas tablas

In [88]:
df_rutas_or = pd.merge(left=df_rutas, right=df_aerop,
                      how='left', left_on='cod_aeropuerto_ori', right_on='cod_aeropuerto')

In [91]:
df_rutas_or.head(5)

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,cod_aeropuerto,nombre_aeropuerto
0,1,2965,2990,00410,2965,Sochi
1,2,2966,2990,00410,2966,Astrakhan
2,3,2966,2962,00410,2966,Astrakhan
3,4,2968,2990,00410,2968,Balandino
4,5,2968,4078,00410,2968,Balandino

#### Ahora hay que validar si hay nulos

In [96]:
df_rutas_or[df_rutas_or['cod_aeropuerto'].isnull()]

Empty DataFrame
Columns: [cod_ruta, cod_aeropuerto_ori, cod_aeropuerto_des, cod_aerolinea, cod_aeropuerto, nombre_aeropuerto]
Index: []

#### Se realiza ahora la validación de datos de aeropuertos destino - Cruce rutas (aeropuertos destino) - aeropuertos

In [102]:
df_rutas_des = pd.merge(left=df_rutas, right=df_aerop,
                      how='left', left_on='cod_aeropuerto_des', right_on='cod_aeropuerto')

In [105]:
df_rutas_des.head()

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,cod_aeropuerto,nombre_aeropuerto
0,1,2965,2990,00410,2990,Kazan
1,2,2966,2990,00410,2990,Kazan
2,3,2966,2962,00410,2962,Mineralnyye Vody
3,4,2968,2990,00410,2990,Kazan
4,5,2968,4078,00410,4078,Tolmachevo

In [108]:
df_rutas_des[df_rutas_des['cod_aeropuerto'].isnull()]

Empty DataFrame
Columns: [cod_ruta, cod_aeropuerto_ori, cod_aeropuerto_des, cod_aerolinea, cod_aeropuerto, nombre_aeropuerto]
Index: []

#### Ahora hay que validar si hay nulos

## Paso 4 - Validación de Integridad: Comprobar si las aerolíneas de las rutas existen en la tabla dm_aerolineas. En caso de encontrar aerolíneas en el fichero de rutas que no estén en la tabla dm_aerolineas actualizarlos a ‘Z9999’.

In [117]:
df_aerol = pd.read_sql_query('SELECT cod_aerolinea as cod_aerolinea_val, nombre_aerolinea FROM dw_aero.dm_aerolineas', conn)
df_aerol.head()

  cod_aerolinea_val                              nombre_aerolinea
0             00001                                Private flight
1             00002                                   135 Airways
2             00003                                 1Time Airline
3             00004  2 Sqn No 1 Elementary Flying Training School
4             00005                               213 Flight Unit

In [120]:
df_rutas_des.head()

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,cod_aeropuerto,nombre_aeropuerto
0,1,2965,2990,00410,2990,Kazan
1,2,2966,2990,00410,2990,Kazan
2,3,2966,2962,00410,2962,Mineralnyye Vody
3,4,2968,2990,00410,2990,Kazan
4,5,2968,4078,00410,4078,Tolmachevo

In [127]:
df_rutas2 = pd.merge(left=df_rutas_des, right=df_aerol,
                      how='left', left_on='cod_aerolinea', right_on='cod_aerolinea_val')
df_rutas2.head()

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,cod_aeropuerto,nombre_aeropuerto,cod_aerolinea_val,nombre_aerolinea
0,1,2965,2990,00410,2990,Kazan,00410,Aerocondor
1,2,2966,2990,00410,2990,Kazan,00410,Aerocondor
2,3,2966,2962,00410,2962,Mineralnyye Vody,00410,Aerocondor
3,4,2968,2990,00410,2990,Kazan,00410,Aerocondor
4,5,2968,4078,00410,4078,Tolmachevo,00410,Aerocondor

#### Validamos si hay nulos

In [135]:
df_rutas2.isnull().sum()

cod_ruta              0
cod_aeropuerto_ori    0
cod_aeropuerto_des    0
cod_aerolinea         0
cod_aeropuerto        0
nombre_aeropuerto     0
cod_aerolinea_val     1
nombre_aerolinea      1
dtype: int64

In [130]:
df_rutas2[df_rutas2['cod_aerolinea_val'].isnull()]

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,cod_aeropuerto,nombre_aeropuerto,cod_aerolinea_val,nombre_aerolinea
11,12,2922,6969,20410,6969,Begishevo,NaN,NaN

In [138]:
df_rutas2[df_rutas2['nombre_aerolinea'].isnull()]

,cod_ruta,cod_aeropuerto_ori,cod_aeropuerto_des,cod_aerolinea,cod_aeropuerto,nombre_aeropuerto,cod_aerolinea_val,nombre_aerolinea
11,12,2922,6969,20410,6969,Begishevo,NaN,NaN

In [144]:
df_rutas2.loc[df_rutas2['cod_aerolinea_val'].isnull(), 'cod_aerolinea'] = 'Z9999'

In [147]:
df_rutas2.loc[df_rutas2['nombre_aerolinea'].isnull(), 'nombre_aerolinea'] = 'Z9999'

## Paso 5: Realizar el volcado final a la tabla hc_rutas

In [153]:
df_rutas2.drop(['cod_aeropuerto','nombre_aeropuerto','cod_aerolinea_val','nombre_aerolinea'], axis=1, inplace=True)
df_rutas2.head(5)

   cod_ruta cod_aeropuerto_ori cod_aeropuerto_des cod_aerolinea
0         1               2965               2990         00410
1         2               2966               2990         00410
2         3               2966               2962         00410
3         4               2968               2990         00410
4         5               2968               4078         00410

In [157]:
# df_rutas2.to_sql('hc_rutas', schema='dw_aero', con = conn, if_exists = 'append', index=False)

In [160]:
count_db = pd.read_sql("SELECT COUNT(*) AS count FROM dw_aero.hc_rutas", conn).iloc[0, 0]
count_df = len(df_rutas2)

print(f"Filas en DataFrame: {count_df}")
print(f"Filas en tabla dw_aero.hc_rutas: {count_db}")

if count_df == count_db:
    print("La carga se efectuó correctamente.")
else:
    print("Hay discrepancias en la cantidad de filas insertadas.")

Filas en DataFrame: 67663
Filas en tabla dw_aero.hc_rutas: 67663
La carga se efectuó correctamente.

## Paso 6: Crear un Dataframe donde se muestre el número de rutas de cada aeropuerto origen, mostrando el código de aeropuerto. Ordenar el resultado de forma que aparezcan en los resultados en las primeras filas los aeropuertos con más rutas (los datos de este nuevo Dataframe lo puede obtener a partir de una consulta a la tabla hc_rutas o del Dataframe utilizado para volcar los datos)

In [166]:
df_num_rutas = (
    df_rutas2['cod_aeropuerto_ori']
    .value_counts()
    .reset_index(name='numero_rutas')
    .rename(columns={'index': 'cod_aeropuerto'})
    .sort_values(by='numero_rutas', ascending=False)
)
df_num_rutas.head(10)

  cod_aeropuerto_ori  numero_rutas
0               3682           915
1               3830           558
2               3364           535
3               0507           527
4               1382           524
5               0340           497
6               3484           492
7               3670           469
8               3797           456
9               0580           453

## Paso 7: Crear otro Dataframe para ver los mismos resultados que el paso anterior, pero en este caso mostrando el nombre del aeropuerto.

In [171]:
df_aerop = pd.read_sql_query('SELECT cod_aeropuerto, nombre_aeropuerto FROM dw_aero.dm_aeropuertos', conn)
df_aerop.head()

  cod_aeropuerto           nombre_aeropuerto
0           0001                      Goroka
1           0002                      Madang
2           0003                 Mount Hagen
3           0004                      Nadzab
4           0005  Port Moresby Jacksons Intl

In [174]:
df_num_rutas.head()

  cod_aeropuerto_ori  numero_rutas
0               3682           915
1               3830           558
2               3364           535
3               0507           527
4               1382           524

In [180]:
df_nom_num_rutas = pd.merge(left=df_num_rutas, right=df_aerop,
                      how='left', left_on='cod_aeropuerto_ori', right_on='cod_aeropuerto')
df_nom_num_rutas.head()

,cod_aeropuerto_ori,numero_rutas,cod_aeropuerto,nombre_aeropuerto
0,3682,915,3682,Hartsfield Jackson Atlanta Intl
1,3830,558,3830,Chicago Ohare Intl
2,3364,535,3364,Capital Intl
3,0507,527,0507,Heathrow
4,1382,524,1382,Charles De Gaulle

In [183]:
df_nom_num_rutas.drop(['cod_aeropuerto'], axis=1, inplace=True)

In [187]:
df_orden_rutas = df_nom_num_rutas[['nombre_aeropuerto','cod_aeropuerto_ori','numero_rutas']]
df_orden_rutas.head(10)

                 nombre_aeropuerto cod_aeropuerto_ori  numero_rutas
0  Hartsfield Jackson Atlanta Intl               3682           915
1               Chicago Ohare Intl               3830           558
2                     Capital Intl               3364           535
3                         Heathrow               0507           527
4                Charles De Gaulle               1382           524
5                   Frankfurt Main               0340           497
6                 Los Angeles Intl               3484           492
7           Dallas Fort Worth Intl               3670           469
8              John F Kennedy Intl               3797           456
9                         Schiphol               0580           453